### ISSUE TITLE
Enable different SV types in the simulation via config

### ISSUE THREAD

**Issue by arnikz** [GooglingTheCancerGenome/sv-gen#11]

**Comment by arnikz** [comment]
@lsantuari: I'm not sure what to do with [these](https://github.com/GooglingTheCancerGenome/sv-gen/blob/ffbef0c3a0943705c485da0f54dbf1f9c80cc1fe/snakemake/analysis.yaml#L28-L29).

**Comment by lsantuari** [comment]
We consider only "simple" SV events in the sv-gen pipeline (INS, DEL, DUP, INV and TRA). We do not consider nested events (INVDEL or INVDUP).
