### ISSUE TITLE
Reads generated from hmz.fasta and hmz-sv.fasta are not mapped

### ISSUE THREAD

**Issue by lsantuari** [GooglingTheCancerGenome/sv-gen#12]
There is a problem with the mapping of the reads generated from hmz.fasta

`bwa mem -R '@RG\tID:hmz\tLB:hmz\tSM:hmz' data/hmz.fasta data/r150_i300/hmz_1.fq data/r150_i300/hmz_2.fq`

and hmz-sv.fasta

`bwa mem -R '@RG\tID:hmz-sv\tLB:hmz-sv\tSM:hmz-sv' data/hmz-sv.fasta data/r150_i300/hmz-sv_1.fq data/r150_i300/hmz-sv_2.fq`

This are the first lines of the output:

_[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 66668 sequences (10000200 bp)...
[M::process] read 66668 sequences (10000200 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 0, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] skip orientation FR as there are not enough pairs
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 66668 reads in 6.748 CPU sec, 6.756 real sec
[M::process] read 66668 sequences (10000200 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 0, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] skip orientation FR as there are not enough pairs
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 66668 reads in 6.817 CPU sec, 7.068 real sec_

The value of FR (Forward-Reverse) reads should be greater than 0.

**Comment by arnikz** [comment]
It's an issue with the config `analysis.yaml` rather than a bug. I've changed the `sv_type` defaults in the config (i.e., introduced only `INDEL`(s)).  The log shows now:

```
+ bwa mem -R '@RG\tID:htz-sv\tLB:htz-sv\tSM:htz-sv' data/htz-sv.fasta data/r150_i500/htz-sv_1.fq data/r150_i500/htz-sv_2.fq
+ samtools sort -o data/r150_i500/cov30/htz-sv.bam
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 24150 sequences (3622500 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 17, 0, 0)
```

Or do you think we should introduce all SV types?

**Comment by lsantuari** [comment]
Can you commit the config `analysis.yaml` that you used?
I added a smaller [FASTA file](https://github.com/GooglingTheCancerGenome/sv-gen/blob/master/snakemake/data/chr22.44Mb_45Mb.GRCh37.fa) that can be used as `test.fasta`.

**Comment by arnikz** [comment]
> Can you commit the config `analysis.yaml` that you used?

The latest config is in the `dev` branch. However, I see now that the mapping problem still remains for `hmz.bam` and `hmz-sv.bam` while `htz-sv.bam` looks fine.

> I added a smaller [FASTA file](https://github.com/GooglingTheCancerGenome/sv-gen/blob/master/snakemake/data/chr22.44Mb_45Mb.GRCh37.fa) that can be used as `test.fasta`.

I've moved the file [here](/GooglingTheCancerGenome/sv-gen/blob/dev/snakemake/data/chr22_44-45Mb.GRCh37.fasta) from `master`.

**Comment by arnikz** [comment]
Could you check [here](https://travis-ci.org/GooglingTheCancerGenome/sv-gen/jobs/634216676)?
