### ISSUE TITLE
Convert SURVIVOR output in BED to BEDPE

### ISSUE THREAD

**Issue by arnikz** [GooglingTheCancerGenome/sv-gen#14]
In fact, SURVIVOR writes TSV file. See an example below:

```
22      636172  22      636261  DEL
22      869827  22      870124  INS
```

**Comment by lsantuari** [comment]
As in the [SURVIVOR Wiki](https://github.com/fritzsedlazeck/SURVIVOR/wiki/Methods-and-Parameter), the line for the reported SV depends on the SV type:

When SVTYPE is either DEL, INS, INV or DUP:

`chr1 start chr1 end SVTYPE`

as in:

`22      636172  22      636261  SVTYPE`

We want to convert it in [BEDPE](https://bedtools.readthedocs.io/en/latest/content/general-usage.html) format:

`chr1 start start+1 chr1 end end+1 SVTYPE`

When SVTYPE is TRA:

`chr1 start1 chr2 start2 SVTYPE chr1 end1 chr2 end2 SVTYPE`

as in:

`22 31778779 21 40771179 TRA 22 31778881 21 40771281 TRA`

In BEDPE format can be arranged in two lines:

```
chr1 start1 start1+1 chr2 start2 start2+1
chr1 end1 end1+1 chr2 end2 end2+1
```

**Comment by arnikz** [comment]
@lsantuari: which file conversion would you prefer?

- BED to BEDPE by extending [this](https://github.com/GooglingTheCancerGenome/CNN/blob/ec7018895befc7c13bc195b1c5149667e643d2fc/run_local.sh#L25) _ad hoc_ code snippet or
- VCF to BEDPE using e.g. [svtools](https://github.com/hall-lab/svtools) (new dependency)

**Comment by lsantuari** [comment]
sv-gen already generates a VCF output with SURVIVOR simSV. Since the SURVIVOR "BED" (TSV) file can contain a [different number of fields](https://github.com/fritzsedlazeck/SURVIVOR/wiki/Methods-and-Parameter) based on the SV type generated, we should use the SURVIVOR VCF file.

**Comment by arnikz** [comment]
> sv-gen already generates a VCF output with SURVIVOR simSV. Since the SURVIVOR "BED" (TSV) file can contain a [different number of fields](https://github.com/fritzsedlazeck/SURVIVOR/wiki/Methods-and-Parameter) based on the SV type generated, we should use the SURVIVOR VCF file.

OK. Have you tested the _svtools_ for VCF->BED(PE) conversion or should we use something else?

**Comment by lsantuari** [comment]
I have not tested _svtools_ yet.
We will use the VCF file generated by SURVIVOR simSV. I will check it for all the SV types.
