### ISSUE TITLE
SURVIVOR VCF files are malformed

### ISSUE THREAD

**Issue by lsantuari** [GooglingTheCancerGenome/sv-gen#33]
`hmz-sv.vcf` and `htz-sv.vcf` (and I suppose also `hmz.vcf,` but it is empty) are malformed.

In the header, `hmz-sv.vcf` does not include the sample name. It currently is as follows:

`#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT`

and it should be, with tab separator:

`#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	HMZ-SV`

Same for `htz-sv.vcf`:

`#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	HTZ-SV`

**Comment by arnikz** [comment]
Thanks for reporting. However, _malformed_  is perhaps an overstatement. According to the [VCFv4.2](https://samtools.github.io/hts-specs/VCFv4.2.pdf) spec (section 1.3), only the first 8 columns are mandatory. I agree that FORMAT followed by SAMPLE ID(s) would have been more complete. Is this critical for your downstream analysis? If so, please file an issue for SURVIVOR. In addition, I upgraded SURVIVOR to v1.0.7 but SAMPLE ID(s) is still missing.

SURVIVOR-related issue #14

**Comment by lsantuari** [comment]
Thank you for pointing it out. The sample name in the VCF header for the Genotype fields is optional. [IGV](http://software.broadinstitute.org/software/igv/) does not allow you to load VCF files without sample names. In our downstream analysis it is not a problem, since each SURVIVOR VCF file refer to a single sample. Given that the SURVIVOR VCF file correctly follows the [VCFv4.2](https://samtools.github.io/hts-specs/VCFv4.2.pdf) specs, there is no reason to open an issue for SURVIVOR.
