### ISSUE TITLE
SURVIVOR requires minimum two chromosomes

### ISSUE THREAD

**Issue by lsantuari** [GooglingTheCancerGenome/sv-gen#34]
SV simulation with SURVIVOR v1.0.7 does not work with a single chromosome. This is because to simulate (inter-chromosomal) translocations you need at least two chromosomes. Strangely, this happens also when you specify 0 for the number of translocations in the analysis.yaml file.
I suggest to update the test data with two chromosomes using the FASTA file in the CNN test data. We should also establish if the >2 chromosomes requirement has been added in the latest (v1.0.7) version of SURVIVOR.

**Comment by arnikz** [comment]
> SV simulation with SURVIVOR v1.0.7 does not work with a single chromosome.

I'm not sure if I understand you correctly. According to CI all is running fine with a [single](https://github.com/GooglingTheCancerGenome/sv-gen/blob/fd9ae777d3aa3fc130525ffd5664c76bfe9280b0/snakemake/analysis.yaml#L7) chromosome.

> This is because to simulate (inter-chromosomal) translocations you need at least two chromosomes.

I agree that two chromosomes are needed to detect translocations.

>Strangely, this happens also when you specify 0 for the number of translocations in the analysis.yaml file.

Could you clarify what you mean by 'this'?

> I suggest to update the test data with two chromosomes using the FASTA file in the CNN test data. We should also establish if the >2 chromosomes requirement has been added in the latest (v1.0.7) version of SURVIVOR.

OK.

**Comment by arnikz** [comment]
I've enabled `tra` in addition to `indel`(s). OK?

**Comment by arnikz** [comment]
The requirement of more than one chromosome to generate (inter-chrom.) translocation was addressed in #40.
