### ISSUE TITLE
The two SV files generated with SURVIVOR are the same

### ISSUE THREAD

**Issue by lsantuari** [GooglingTheCancerGenome/sv-gen#35]
@arnikz I cannot explain why `hmz-sv` and `htz-sv` [generated independently](https://github.com/GooglingTheCancerGenome/sv-gen/blob/master/doc/sv-gen.svg) by SURVIVOR SV are the same file. Could it be that the random seed used by SURVIVOR is the same? However, simSV does not have a seed among its input parameters.

@arnikz Could you look into it?

**Comment by arnikz** [comment]
> @arnikz I cannot explain why `hmz-sv` and `htz-sv` [generated independently](https://github.com/GooglingTheCancerGenome/sv-gen/blob/master/doc/sv-gen.svg) by SURVIVOR SV are the same file. 

Which files do you mean? For example, the corresponding BED or BAM files are not the same:

```bash
$ md5sum *.bed
d5d6f45430ee127cc8ba7aa8e074e407  hmz-sv.bed
33d0abe203e7b07447abe8eafcda19b6  htz-sv.bed

$ samtools view -h hmz-sv.bam|wc -l
400365

$ samtools view -h htz-sv.bam|wc -l
400119
```

> Could it be that the random seed used by SURVIVOR is the same? However, simSV does not have a seed among its input parameters.

Indeed, contrary to ART there is no such input parameter in SURVIVOR (opened [this issue](https://github.com/fritzsedlazeck/SURVIVOR/issues/119)). I don't expect the use of a hard-coded seed. In addition, SURVIVOR runs for each genotype separately.

**Comment by arnikz** [comment]
Should we close this issue?
