### ISSUE TITLE
TMP directory in samtools sort

### ISSUE THREAD

**Issue by lsantuari** [GooglingTheCancerGenome/sv-gen#38]
In the _analysis.yaml_ file, a TMP directory can be specified where the temporary files generated by [samtools sort](https://github.com/GooglingTheCancerGenome/sv-gen/blob/fd9ae777d3aa3fc130525ffd5664c76bfe9280b0/snakemake/rules/map_reads.smk#L49) are temporarily stored. To achieve this, we could use the [`-T` option](http://www.htslib.org/doc/samtools-sort.html) available in `samtools sort`.

**Comment by arnikz** [comment]
Run a large-scale simulation according to config in `/project/gcg/Data/sv-gen/coverage/snakemake/analysis.yaml`).
